
Unknown functions:
  compile:file/2
  compile:forms/2
  compile:noenv_forms/2
  compile:output_generated/1
  crypto:block_decrypt/4
  crypto:start/0
  erl_prim_loader:get_cwd/0
  erl_prim_loader:get_cwd/1
  erl_prim_loader:get_file/1
  erl_prim_loader:get_modules/3
  erl_prim_loader:get_path/0
  erl_prim_loader:is_basename/1
  erl_prim_loader:list_dir/1
  erl_prim_loader:prim_get_cwd/2
  erl_prim_loader:prim_get_file/2
  erl_prim_loader:prim_init/0
  erl_prim_loader:prim_list_dir/2
  erl_prim_loader:prim_read_file_info/3
  erl_prim_loader:read_file_info/1
  erl_prim_loader:read_link_info/1
  erl_prim_loader:set_primary_archive/4
  erlang:atom_to_list/1
  erlang:binary_to_atom/2
  erlang:binary_to_integer/1
  erlang:binary_to_integer/2
  erlang:binary_to_list/1
  erlang:binary_to_list/3
  erlang:binary_to_term/1
  erlang:bitstring_to_list/1
  erlang:call_on_load_function/1
  erlang:cancel_timer/1
  erlang:cancel_timer/2
  erlang:convert_time_unit/3
  erlang:delete_module/1
  erlang:demonitor/1
  erlang:demonitor/2
  erlang:disconnect_node/1
  erlang:display/1
  erlang:display_string/1
  erlang:dist_get_stat/1
  erlang:dt_restore_tag/1
  erlang:dt_spread_tag/1
  erlang:erase/0
  erlang:erase/1
  erlang:exit/2
  erlang:external_size/1
  erlang:finish_loading/1
  erlang:float_to_binary/1
  erlang:float_to_list/1
  erlang:fun_info/2
  erlang:fun_info_mfa/1
  erlang:fun_to_list/1
  erlang:function_exported/3
  erlang:garbage_collect/0
  erlang:garbage_collect/1
  erlang:get/0
  erlang:get/1
  erlang:get_module_info/1
  erlang:get_module_info/2
  erlang:group_leader/0
  erlang:group_leader/2
  erlang:has_prepared_code_on_load/1
  erlang:hibernate/3
  erlang:integer_to_binary/1
  erlang:integer_to_list/1
  erlang:integer_to_list/2
  erlang:iolist_size/1
  erlang:iolist_to_binary/1
  erlang:iolist_to_iovec/1
  erlang:is_alive/0
  erlang:is_builtin/3
  erlang:is_process_alive/1
  erlang:link/1
  erlang:list_to_atom/1
  erlang:list_to_binary/1
  erlang:list_to_existing_atom/1
  erlang:list_to_float/1
  erlang:list_to_integer/1
  erlang:list_to_integer/2
  erlang:list_to_pid/1
  erlang:list_to_port/1
  erlang:list_to_ref/1
  erlang:list_to_tuple/1
  erlang:load_module/2
  erlang:localtime/0
  erlang:localtime_to_universaltime/1
  erlang:localtime_to_universaltime/2
  erlang:make_ref/0
  erlang:match_spec_test/3
  erlang:max/2
  erlang:md5/1
  erlang:md5_final/1
  erlang:md5_init/0
  erlang:md5_update/2
  erlang:memory/0
  erlang:memory/1
  erlang:min/2
  erlang:module_loaded/1
  erlang:monitor/2
  erlang:monitor_node/2
  erlang:monitor_node/3
  erlang:monotonic_time/0
  erlang:monotonic_time/1
  erlang:nodes/0
  erlang:nodes/1
  erlang:open_port/2
  erlang:phash/2
  erlang:phash2/1
  erlang:pid_to_list/1
  erlang:port_close/1
  erlang:port_command/2
  erlang:port_connect/2
  erlang:port_control/3
  erlang:port_get_data/1
  erlang:port_info/2
  erlang:port_set_data/2
  erlang:port_to_list/1
  erlang:ports/0
  erlang:posixtime_to_universaltime/1
  erlang:pre_loaded/0
  erlang:prepare_loading/2
  erlang:process_display/2
  erlang:process_flag/2
  erlang:process_info/1
  erlang:process_info/2
  erlang:processes/0
  erlang:put/2
  erlang:raise/3
  erlang:read_timer/1
  erlang:ref_to_list/1
  erlang:register/2
  erlang:registered/0
  erlang:send/2
  erlang:send/3
  erlang:send_after/3
  erlang:send_nosuspend/2
  erlang:seq_trace/2
  erlang:seq_trace_info/1
  erlang:seq_trace_print/1
  erlang:seq_trace_print/2
  erlang:setnode/2
  erlang:setnode/3
  erlang:spawn/1
  erlang:spawn/3
  erlang:spawn/4
  erlang:spawn_link/1
  erlang:spawn_link/3
  erlang:spawn_link/4
  erlang:spawn_monitor/1
  erlang:spawn_monitor/3
  erlang:spawn_opt/2
  erlang:spawn_opt/4
  erlang:spawn_opt/5
  erlang:split_binary/2
  erlang:start_timer/3
  erlang:start_timer/4
  erlang:statistics/1
  erlang:system_flag/2
  erlang:system_time/0
  erlang:term_to_binary/1
  erlang:term_to_binary/2
  erlang:time_offset/0
  erlang:timestamp/0
  erlang:unique_integer/0
  erlang:unique_integer/1
  erlang:universaltime/0
  erlang:universaltime_to_localtime/1
  erlang:unlink/1
  erlang:unregister/1
  erlang:whereis/1
  erlang:yield/0
  erts_code_purger:finish_after_on_load/2
  erts_code_purger:purge/1
  erts_code_purger:soft_purge/1
  erts_internal:abort_pending_connection/2
  erts_internal:get_dflags/0
  erts_internal:map_hashmap_children/1
  erts_internal:map_next/3
  erts_internal:map_to_tuple_keys/1
  erts_internal:new_connection/1
  erts_internal:scheduler_wall_time/1
  erts_internal:system_check/1
  erts_internal:term_type/1
  init:archive_extension/0
  init:code_path_choice/0
  init:ensure_loaded/1
  init:fetch_loaded/0
  init:get_argument/1
  init:get_arguments/0
  init:get_plain_arguments/0
  init:notify_when_started/1
  init:objfile_extension/0
  init:run_on_load_handlers/0
  init:stop/0
  init:wait_until_started/0
  persistent_term:get/1
  persistent_term:put/2
  prim_buffer:find_byte_index/2
  prim_buffer:new/0
  prim_buffer:read/2
  prim_buffer:read_iovec/2
  prim_buffer:size/1
  prim_buffer:try_lock/1
  prim_buffer:unlock/1
  prim_buffer:wipe/1
  prim_buffer:write/2
  prim_eval:'receive'/2
  prim_file:altname/1
  prim_file:close/1
  prim_file:copy/3
  prim_file:del_dir/1
  prim_file:delete/1
  prim_file:get_cwd/0
  prim_file:get_cwd/1
  prim_file:list_dir/1
  prim_file:list_dir_all/1
  prim_file:make_dir/1
  prim_file:make_link/2
  prim_file:make_symlink/2
  prim_file:open/2
  prim_file:read_file/1
  prim_file:read_file_info/1
  prim_file:read_file_info/2
  prim_file:read_link/1
  prim_file:read_link_all/1
  prim_file:read_link_info/1
  prim_file:read_link_info/2
  prim_file:rename/2
  prim_file:set_cwd/1
  prim_file:write_file/2
  prim_file:write_file_info/2
  prim_file:write_file_info/3
  prim_inet:accept/1
  prim_inet:accept/2
  prim_inet:accept/3
  prim_inet:bind/3
  prim_inet:chgopts/2
  prim_inet:close/1
  prim_inet:connect/3
  prim_inet:connect/4
  prim_inet:fdopen/5
  prim_inet:getfd/1
  prim_inet:gethostname/1
  prim_inet:getifaddrs/1
  prim_inet:getiflist/1
  prim_inet:getopt/2
  prim_inet:getopts/2
  prim_inet:getservbyname/3
  prim_inet:getservbyport/3
  prim_inet:getstat/2
  prim_inet:getstatus/1
  prim_inet:gettype/1
  prim_inet:ifget/3
  prim_inet:ifset/3
  prim_inet:ignorefd/2
  prim_inet:is_sockopt_val/2
  prim_inet:listen/2
  prim_inet:open/4
  prim_inet:peeloff/2
  prim_inet:peername/1
  prim_inet:peernames/1
  prim_inet:peernames/2
  prim_inet:recv/2
  prim_inet:recv/3
  prim_inet:recvfrom/2
  prim_inet:recvfrom/3
  prim_inet:send/2
  prim_inet:send/3
  prim_inet:sendmsg/3
  prim_inet:sendto/4
  prim_inet:setopt/3
  prim_inet:setopts/2
  prim_inet:setpeername/2
  prim_inet:setsockname/2
  prim_inet:shutdown/2
  prim_inet:sockname/1
  prim_inet:socknames/1
  prim_inet:socknames/2
  prim_inet:unrecv/2
  prim_net:command/1
  prim_net:getaddrinfo/2
  prim_net:gethostname/0
  prim_net:getifaddrs/1
  prim_net:getnameinfo/2
  prim_net:if_index2name/1
  prim_net:if_name2index/1
  prim_net:if_names/0
  prim_net:info/0
  prim_zip:close/1
  prim_zip:open/3
  socket:ensure_sockaddr/1
  zlib:close/1
  zlib:crc32/1
  zlib:crc32/2
  zlib:crc32/3
  zlib:deflate/2
  zlib:deflate/3
  zlib:deflateEnd/1
  zlib:deflateInit/6
  zlib:inflate/2
  zlib:inflateEnd/1
  zlib:inflateInit/2
  zlib:inflateInit/3
  zlib:inflateReset/1
  zlib:open/0
Unknown types:
  compile:option/0
  erlang:time_unit/0
  erlang:timestamp/0
  socket:domain/0
  socket:protocol/0
  socket:sockaddr/0
  socket:type/0
